_wandb:
    value:
        cli_version: 0.18.5
        code_path: code/src/set_transformer_small.py
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 50
eval_freq:
    value: 0
learning_rate:
    value: 0.001
n_embd:
    value: 64
n_head:
    value: 2
n_layer:
    value: 2
patience:
    value: 3
